### ISSUE TITLE
How to use Q/A

### ISSUE THREAD

**Issue by kwikcoins** [Wladastic/Auto-GPT-Telegram-Plugin#1]
How do I communicate with the bot via telegram on my mobile? I have the telegram plugin cloned and zipped and have added the info to my .env I just cant figure out how to communicate with it

**Comment by Wladastic** [comment]
It will start working once the other 2 pr's are in Auto-GPT and Auto-GPT-plugin-template

**Comment by Wladastic** [comment]
Also please read the Readme.

**Comment by kwikcoins** [comment]
root@Auto:~/Auto-GPT# python3 -m autogpt
NEWS:  Welcome to Auto-GPT! We'll keep you informed of the latest news and features by printing messages here. If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag
WARNING:  You are running on `master` branch - this is not a supported branch.
WARNNG Plugin AutoGPTTelegram found. But not in the whitelist... Load? (y/n): y
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/Auto-GPT/autogpt/cli.py", line 130, in main
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/root/Auto-GPT/autogpt/plugins.py", line 227, in scan_plugins
    loaded_plugins.append(a_module())
  File "/usr/local/lib/python3.10/dist-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class AutoGPTTelegram with abstract methods can_handle_chat_completion, can_handle_on_instruction, can_handle_on_planning, can_handle_on_response, can_handle_post_command, can_handle_post_instruction, can_handle_post_planning, can_handle_post_prompt, can_handle_pre_command, can_handle_pre_instruction, can_handle_report, can_handle_user_input, handle_chat_completion, on_instruction, on_planning, on_response, post_command, post_instruction, post_planning, post_prompt, pre_command, pre_instruction, report, user_input
root@Auto:~/Auto-GPT#

**Comment by kwikcoins** [comment]
This is what I get when trying to start autogpt

**Comment by Wladastic** [comment]
Thats just what I said, the template is missing the report and user_input methods, so it cannot be casted into the proper object.

**Comment by kwikcoins** [comment]
Sorry this is all new to me and im just trying to figure it out with my limited knowledge

**Comment by Wladastic** [comment]
Until then, feel free to use this branch:
https://github.com/Wladastic/Auto-GPT-Telegram

I built this plugin as an integration first, so this is where it still works.

**Comment by Wladastic** [comment]
> Sorry this is all new to me and im just trying to figure it out with my limited knowledge

no problem, I am happy to answer any questions.

**Comment by kwikcoins** [comment]
> Until then, feel free to use this branch:
> 
> https://github.com/Wladastic/Auto-GPT-Telegram
> 
> 
> 
> I built this plugin as an integration first, so this is where it still works.

I used this everything all setup, the bot has access to messages on telegram it send message to the group just fine but when I send any type of response it just keeps polling like it cant see my request in telegram.

**Comment by Wladastic** [comment]
a group?

**Comment by kwikcoins** [comment]
> a group?

I tried using the chat id of the group I added the bot to because when I added the chat id of the bot I got an error stating that messages cant be sent to itself

**Comment by Wladastic** [comment]
I am glad, because you only need the chat_id, not the bot id.

For anyone who jumps in:
To get the chat_id, first create the bot using botfaher,
once done, send a chat message to your bot and retrieve the chat_id through getUpdates Call

**Comment by Wladastic** [comment]
Hello, please await the pr that makes it runnable first.

**Comment by findingdolla** [comment]
SO just to confirm, even with cloning your version of AutoGPT it doesn't work just yet?

**Comment by Wladastic** [comment]
No, the Plugin won't work, the fork with telegram built in, does not need the plugin.
Please don't mix those two up.
The plugin is the same functionality built as a plugin, while the Auto-GPT-Telegram repo has it built in already.

**Comment by Wladastic** [comment]
Significant Gravitas is already informed, once they update the package on python pip lib, then this PR will be merged and you can use the plugin:
https://github.com/Significant-Gravitas/Auto-GPT/pull/2929
Then the plugin works. :)
Sorry for the confusion, the telegram functionality was already done, but we decided to make it a plugin instead, which needs some extra time.

**Comment by Wladastic** [comment]
Happy to know!
I will close this once the other PR's went through, that make the Plugin work.

**Comment by proitservices** [comment]
Hi Wladstic, 
I got that plugin showing up on AutoGPT but not working due to the PRs you mentioned. Any eta you can throw at it?
Nice work btw - really needed functionality

**Comment by proitservices** [comment]
I am a DevOps guy but probably can help out if you need a hand on the project. 

Peter

**Comment by Wladastic** [comment]
got it running! :)
https://github.com/Significant-Gravitas/Auto-GPT/pull/2929
once that is through, please pull the plugin again as I had to change some things

**Comment by proitservices** [comment]
Amazing - can't wait to test. Was looking already to develop my own.
In the meantime added a feature to the commands to use a local gpt4all for agent queries. Quicker turn around for code gen.

**Comment by Wladastic** [comment]
PR is done, it should work now!
