### ISSUE TITLE
feature suggestion: possibility to have a command to reload AutoGpt with a new ai-settings.yml ? 

### ISSUE THREAD

**Issue by barrymac** [Wladastic/Auto-GPT-Telegram-Plugin#14]
Love this work! Thank you!

I think it would be very useful to have the bot be able to change the central goals of the autoGPT instance. 

I have an instance running on a server, and having telegram access is really nice to have when I'm out of the house and something may come to mind to have AutoGPT work on and come home to freshly baked completed tasks. 

I'm not sure how this would be achieved with AutoGPT in int's current form, but I expect a lot of architecture changes are in the pipeline.

**Comment by Wladastic** [comment]
Hello,
This is already in work
