### ISSUE TITLE
Can't read .env from Docker

### ISSUE THREAD

**Issue by helionaut** [Wladastic/Auto-GPT-Telegram-Plugin#17]
Hello! Thank you for your excellent work!

I am using Telegram plugin from Docker, Windows.
I got the error:
```
  File "plugins/Auto-GPT-Telegram-Plugin-master.zip/Auto-GPT-Telegram-Plugin-master/src/telegram_plugin/__init__.py", line 15, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/app/.env'
```

Every time I started AutoGPT, I had to "docker cp" .env file to the running Docker container. I used https://github.com/ppetermann/Auto-GPT-DockerSetup to prepare Docker.

I can't understand where is the issue - the way how .env is read or the Docker itself..

**Comment by Wladastic** [comment]
Please update autogpt or use the stable branch.
