### ISSUE TITLE
Messages sent to telegram include colour Coding

### ISSUE THREAD

**Issue by frankymcgee** [Wladastic/Auto-GPT-Telegram-Plugin#2]
• Plugin communicates with Telegram upon startup
• Any Colouring from the Auto-GPT after the welcome back! prompt is passed through to the Telegram Bot
![image](https://user-images.githubusercontent.com/46082212/234733805-4d4164f6-e73c-4b45-b624-9ba91da3a773.png)
![image](https://user-images.githubusercontent.com/46082212/234733829-54537dd8-137e-4122-98fa-a735d595b124.png)

**Comment by Wladastic** [comment]
I also noticed that, it's an issue within some of auto-gpt's logs.
Already communicated it towards them.
Adding a filter for those colour codes seems to intrusive from my end.

**Comment by Wladastic** [comment]
fixed in new version.
