### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by crushingCodes** [Wladastic/Auto-GPT-Telegram-Plugin#4]
Hi, thanks for making this plugin, just not sure how to get it up and running. 
The steps I have tried are:
- checked out most recent commit of autogpt master
- cloned this telegram plugin repo in the autogpt plugins folder
- Added the following to my .env
```
ALLOWLISTED_PLUGINS=Telegram

CHAT_MESSAGES_ENABLED=True
TELEGRAM_API_KEY="*******************************************"
TELEGRAM_CHAT_ID=************
```
Run using the following command
`docker compose run --build --rm auto-gpt`

Do I need to run it differently?

Also not sure if anyone knows how to run it in debug mode using docker compose?

If I can get it running, Im happy to put up a pr to improve instructions

**Comment by rastrat** [comment]
@Wladastic

**Comment by zenchantlive** [comment]
I also have no idea how to actually get my bot to respond after completing all the steps

**Comment by Wladastic** [comment]
Make sure to have:
TELEGRAM_API_KEY=
TELEGRAM_CHAT_ID=
ALLOWLISTED_PLUGINS=AutoGPTTelegram
CHAT_MESSAGES_ENABLED=True
within your .env file.
Also keep in mind to use the official documentation on how to use plugins.

**Comment by Wladastic** [comment]
Please keep in mind that I live in another timezone, tagging me won’t make me respond quicker :P
Those messages arrived at 4 am

**Comment by rastrat** [comment]
@Wladastic  that all works ive got all the credentials setup bi im not receiving msgs in telegram

**Comment by Wladastic** [comment]
Did you make sure to have the correct id in?
Feel free to reach out on discord

**Comment by rastrat** [comment]
@Wladastic yes the 10 digit number code that is provided by botfather before the api key

**Comment by Wladastic** [comment]
You have to message your bot first and obtain the chat Id from that, have you done so?

**Comment by Wladastic** [comment]
You need both api key as well as the chat id

**Comment by Wladastic** [comment]
"chat":{"id":this one should be the id,"first_name":"_","type":"private"}

**Comment by rastrat** [comment]
@Wladastic  i tried no reply

**Comment by Wladastic** [comment]
The bot doesn’t reply if it doesn’t await a question

**Comment by zenchantlive** [comment]
My bot replies just fine, but I can not get autogpt to send messages to it. I have the key and token and permission set up as shown. I have verified it is all correct. Any help would be appreciated. I also was unable to "--install-plugin-deps" which may be the issue.

 What is your discord?

**Comment by crushingCodes** [comment]
thanks for your help
I was able to get it to work by following the instructions here:
[Significant-Gravitas/Auto-GPT-Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins)
and change the first download step to the following and it worked:
`curl -L -o ./plugins/Auto-GPT-Telegram.zip https://github.com/Wladastic/Auto-GPT-Telegram-Plugin/archive/refs/heads/master.zip`
