### ISSUE TITLE
How can we make a reset ability ?

### ISSUE THREAD

**Issue by onuratakan** [Wladastic/Auto-GPT-Telegram-Plugin#5]
Hi, 

its work verry well but ı want to reset in sometimes. We must to add an /reset function and if you give me some ideas i can send  a pr.

Best regards,

**Comment by Wladastic** [comment]
Hi, currently working on that.
/start also doesn't work rn, I am writing a workaround though.
Should be done on the weekend

**Comment by onuratakan** [comment]
Thanks, i will be waiting.
